// ✅ Auto Meta Tags Generator Utility
const generateMetaTags = (product) => {
  const { name, category, brand, description, price } = product;

  // Generate SEO Title (50-60 characters ideal)
  const seoTitle = `${name} - ${category} from ${brand} | Luwia Jewelry`;

  // Generate SEO Description (150-160 characters ideal)
  const seoDescription = description
    ? `Shop ${name} in ${category}. ${description.substring(0, 100)}... Premium ${category} by ${brand}.`
    : `Discover exquisite ${category} - ${name} from Luwia. Premium jewelry and accessories starting from $${price}.`;

  // Generate Keywords
  const keywords = [
    name.toLowerCase(),
    category.toLowerCase(),
    brand.toLowerCase(),
    `${category} for sale`,
    `buy ${category}`,
    `${name} price`,
    `${brand} ${category}`,
    `jewelry ${category}`,
    `affordable ${category}`,
    "Luwia jewelry",
    `${category} collection`,
    `trending ${category}`
  ];

  // Generate SEO-friendly slug
  const seoSlug = name
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .substring(0, 50);

  return {
    seoTitle,
    seoDescription,
    keywords: keywords.slice(0, 10),
    seoSlug,
    metaRobots: "index,follow",
    canonicalUrl: `/products/${seoSlug}`,
    autoGeneratedMetaTags: true
  };
};

module.exports = { generateMetaTags };
