const mongoose = require("mongoose");

const priceHistorySchema = new mongoose.Schema(
  {
    price: { type: Number, required: true },
    changedAt: { type: Date, default: Date.now },
    percentChange: { type: Number, default: 0 }
  },
  { _id: false }
);

const productSchema = new mongoose.Schema({
  name: { type: String, required: true, trim: true },
  price: { type: Number, required: true, min: 0 },
  category: { type: String, default: "General", trim: true },
  brand: { type: String, default: "Luwia", trim: true },
  rating: { type: Number, default: 4, min: 0, max: 5 },
  soldCount: { type: Number, default: 0, min: 0 },
  description: { type: String, default: "" },
  image: { type: String, default: "" },
  
  // ✅ Inventory Management
  stock: { type: Number, default: 100, min: 0 },
  minStockLevel: { type: Number, default: 10, min: 0 },
  reorderQuantity: { type: Number, default: 50, min: 0 },
  lastRestockDate: { type: Date, default: null },
  
  // ✅ Price Tracking
  previousPrice: { type: Number, default: null },
  priceHistory: { type: [priceHistorySchema], default: [] },
  priceChangedAt: { type: Date, default: null },
  
  // ✅ Seasonal & Sales Analytics
  seasonalData: {
    jan: { type: Number, default: 0 },
    feb: { type: Number, default: 0 },
    mar: { type: Number, default: 0 },
    apr: { type: Number, default: 0 },
    may: { type: Number, default: 0 },
    jun: { type: Number, default: 0 },
    jul: { type: Number, default: 0 },
    aug: { type: Number, default: 0 },
    sep: { type: Number, default: 0 },
    oct: { type: Number, default: 0 },
    nov: { type: Number, default: 0 },
    dec: { type: Number, default: 0 }
  },
  
  // ✅ Auto-Generated SEO & Meta Tags
  seoTitle: { type: String, default: "" },
  seoDescription: { type: String, default: "" },
  keywords: { type: [String], default: [] },
  themes: { type: [String], default: [] },
  seoSlug: { type: String, default: "", trim: true },
  metaRobots: { type: String, default: "index,follow" },
  canonicalUrl: { type: String, default: "" },
  autoGeneratedMetaTags: { type: Boolean, default: false },
  
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model("Product", productSchema);